print("     xx   xx     ")
print("     xx   xx     ")
print("     xx   xx     ")
print("     xx   xx     ")
print("     xx   xx     ")
print("                 ")
print("xx             xx")
print(" xx           xx ")
print("  xx         xx  ")
print("   xxxxxxxxxxx   ")
print("Don't Worry Be Happy")
